### ISSUE TITLE
MB is not consistent between huge versions

### ISSUE THREAD

**Issue by zdk123** [HMJiangGatech/huge#10]
A SPIEC-EASI user discovered a discrepancy in the `huge.mb` results at least after the switch to version 1.3 (related issue https://github.com/zdk123/SpiecEasi/issues/107).

In trying to reproduce the error, I found that there are both false negatives and false positive edges typically associated with small [in magnitude] coefficients.

Here's a reproducible example managed by different conda environments:
```sh
conda create -n huge2.7 -c conda-forge r-huge=1.2.7
conda create -n huge3.3 -c conda-forge r-huge=1.3.3
```

Run this in an R session code twice, under each huge version
```r
library(huge)
set.seed(10010)
dat <- huge.generator(100, 215, graph="scale-free", v=.01, u=2)

out <- huge::huge.mb(dat$data, lambda.min.ratio=1e-2, nlambda=10)
save(out, file=paste0('hugev', packageVersion('huge'), ".RData"))
```

Compare results
```r
library(Matrix)
load('hugev1.3.3.RData')
out33 <- out
load('hugev1.2.7.RData')
out27 <- out
rm(out)

sapply(1:length(out27$path), function(i) norm(out33$path[[i]]-out27$path[[i]], '1'))
```

So it seems likely to me that in migrating the source code, maybe the zero tolerance and/or floating point precision has changed. 

I would greatly appreciate some guidance on this, especially if it was a deliberate choice. An option to obtain numerically equivalent results would be highly useful so that users can safely upgrade dependencies without dozens to hundreds of edges changing.

**Comment by HMJiangGatech** [comment]
Hi, I ran through your code and did not see any different between these two versions. 
```
> sapply(1:length(out27$path), function(i) norm(out33$path[[i]]-out27$path[[i]], '1'))
 [1] 0 0 0 0 0 0 0 0 0 0
```

**Comment by zdk123** [comment]
This is very odd... I've tested on separate MacOS and Ubuntu systems and am getting wide deviations.

```
> sapply(1:length(out27$path), function(i) norm(out33$path[[i]]-out27$path[[i]], '1'))
 [1]  0  2  3  5  9 18 29 40 50 62
```

**Comment by HMJiangGatech** [comment]
I was using windows 10. Let me try on Ubuntu.

**Comment by zdk123** [comment]
Would it be helpful for reproducibility if I created a docker container?

**Comment by HMJiangGatech** [comment]
We just fixed the implementation of the MB algorithm. Now it should be the same as 1.2.7. If you find any problems, plz let us know.

**Comment by zdk123** [comment]
Fantastic! I'll test it this weekend and get back to you ASAP.

**Comment by zdk123** [comment]
It seems working on all platforms via conda. Compiling it myself worked on ubuntu but _not_ macOS, at least until I installed R and Rcpp fresh (also from conda, but huge from CRAN). Are there any necessary conditions for compiling the source code that I should pass along to mac users?

thanks!

**Comment by HMJiangGatech** [comment]
There are no additional conditions. The latest package is now available on CRAN.

**Comment by zdk123** [comment]
thanks
