### ISSUE TITLE
For Loop Not Nested Correctly

### ISSUE THREAD

**Issue by acdeboer** [HMJiangGatech/huge#3]
In src/RIC.cpp the for loop on 19 should have parentheses. Because it doesn't, the for loop on line 31 is not actually nested inside of it, unlike what the indentation suggests. The for loop on line 31 isn't actually ever entered, since j == d when line 31 is actually reached.

This causes lambda to be a bit smaller than it actually should be (since you're not looking at as many values when finding lambda_max).

Thank you

**Comment by HMJiangGatech** [comment]
Thanks for your comment. I have already merged the PR.
