### ISSUE TITLE
'huge.mb' is not installed at ver. 1.3 (cran)

### ISSUE THREAD

**Issue by heuklang** [HMJiangGatech/huge#5]
function 'huge.mb' was install at ver. 1.27.
'huge.mb' is not installed at ver. 1.3.

Is it intended?

**Comment by HMJiangGatech** [comment]
That's weird. This will be fixed soon.
Thank you so much.

**Comment by HMJiangGatech** [comment]
It's fixed in 1.3.2

**Comment by heuklang** [comment]
Thank you!
