### ISSUE TITLE
Export huge.mb or return beta

### ISSUE THREAD

**Issue by zdk123** [HMJiangGatech/huge#6]
I was using the output from the `huge.mb` function in my [SpiecEasi](https://github.com/zdk123/SpiecEasi) package, but migrated back to the `huge::huge` wrapper in the recent update to version 1.3.

However, since huge doesn't pass through coefficient matrix (beta) from `huge::huge` I am now missing some key functionality. This is not a problem for "glasso" mode, since icov/cov does get returned.

Would it be possible to (optionally?) return beta and/or export huge.mb as was done prior to version 1.3?

Logging the bug on my end here: https://github.com/zdk123/SpiecEasi/issues/72

thanks!

**Comment by HMJiangGatech** [comment]
Sure. Thanks for your advice, I will release a new version with exporting beta and huge.mb soon.
