### ISSUE TITLE
MB: errors with large data, small lambdas

### ISSUE THREAD

**Issue by zdk123** [HMJiangGatech/huge#8]
Tracking a huge-related error here:
https://github.com/zdk123/SpiecEasi/issues/73

Reproduce with:
```
X <- MASS::mvrnorm(10, rep(0,120), diag(120))
huge::huge(X, method='mb', lambda=c(.1))
```
> Error in validObject(.Object) :
>   invalid class “dgCMatrix” object: all row indices must be between 0 and nrow-1

```
huge::huge(X, method='mb', lambda=c(.01))
```
>  *** caught segfault ***
> address 0x450000003a, cause 'memory not mapped'

**Comment by HMJiangGatech** [comment]
Hi, thanks for pointing out the bug.
This is because of some internal error when connecting Rcpp and R. It will be fixed very soon

**Comment by zdk123** [comment]
Excellent, thank you very much!
