### ISSUE TITLE
MB: negative length vectors are not allowed

### ISSUE THREAD

**Issue by zdk123** [HMJiangGatech/huge#9]
Hi there,

 We've uncovered another bug over at [SpiecEasi](https://github.com/zdk123/SpiecEasi/issues/80) that seems to be related to a toxic combination of parameters (large data sets & when number of lambdas is large).

For instance:
```
dat <- huge::huge.generator(1183, 1510)
out <- huge::huge.mb(dat$data, lambda.min.ratio=1e-2, nlambda=100)
## Conducting Meinshausen & Buhlmann graph estimation (mb)....Error in huge::huge.mb(X, lambda.min.ratio = 0.01, nlambda = 100) :
##  negative length vectors are not allowed

out <- huge::huge.mb(dat$data, lambda.min.ratio=1e-2, nlambda=10)
## NO ERROR

dat <- huge::huge.generator(1511, 1510)
out <- huge::huge.mb(dat$data, lambda.min.ratio=1e-2, nlambda=100)
## NO ERROR
```

The error is getting thrown by the C code, when p < n, oddly and only when nlambda is greater than 20 or so.

thanks!

**Comment by HMJiangGatech** [comment]
Thank you for revealing this issue. This is because we allocate a cache vector that is too large.
